### ISSUE TITLE
Question about other libraries

### ISSUE THREAD

**Issue by Freshblood1121** [yudaapratama/inline-keyboard-calendar#1]
Hello, I really liked your project, but I don’t understand how it can be combined with the  "Telegraph" library Here from "Defstudio",HELP PLEASE :(

**Comment by yudaapratama** [comment]
> Hello, I really liked your project, but I don’t understand how it can be combined with the "Telegraph" library Here from "Defstudio",HELP PLEASE :(

I am not familiar with how a telegraph works. However, you can refer to the `InlineKeyboardCalendar.php` file for guidance on how to generate the calendar button or visit https://github.com/unmonoqueteclea/calendar-telegram for inspiration.

In the near future, I intend to ensure that this library can work seamlessly with other Telegram bots.

**Comment by Freshblood1121** [comment]
Thank you for your answer and I recommend that you familiarize yourself with the "Telegraph" library for PHP -it's very cool😎
